# Generated by Django 2.1.7 on 2019-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('state', models.CharField(default='задача завершилась неудачей', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data', models.FileField(blank=True, upload_to='fileStorage')),
                ('md5', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
